// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.deepsea.mua.stub.entity.proto;

import com.google.protobuf.AbstractMessageLite;

public final class MsgOuterClass {
    private MsgOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Msg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 MsgId = 1;</code>
         */
        int getMsgId();

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        boolean hasData();

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        com.google.protobuf.Any getData();

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();
    }

    /**
     * Protobuf type {@code Msg}
     */
    public static final class Msg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Msg)
            MsgOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Msg.newBuilder() to construct.
        private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Msg() {
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new Msg();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Msg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            msgId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (data_ != null) {
                                subBuilder = data_.toBuilder();
                            }
                            data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(data_);
                                data_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MsgOuterClass.internal_static_Mua_ProtoMsg_Msg_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MsgOuterClass.internal_static_Mua_ProtoMsg_Msg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MsgOuterClass.Msg.class, MsgOuterClass.Msg.Builder.class);
        }

        public static final int MSGID_FIELD_NUMBER = 1;
        private int msgId_;

        /**
         * <code>int32 MsgId = 1;</code>
         */
        public int getMsgId() {
            return msgId_;
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.Any data_;

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        public boolean hasData() {
            return data_ != null;
        }

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <code>.google.protobuf.Any Data = 2;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return getData();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (msgId_ != 0) {
                output.writeInt32(1, msgId_);
            }
            if (data_ != null) {
                output.writeMessage(2, getData());
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (msgId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, msgId_);
            }
            if (data_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MsgOuterClass.Msg)) {
                return super.equals(obj);
            }
            MsgOuterClass.Msg other = (MsgOuterClass.Msg) obj;

            if (getMsgId()
                    != other.getMsgId()) return false;
            if (hasData() != other.hasData()) return false;
            if (hasData()) {
                if (!getData()
                        .equals(other.getData())) return false;
            }
            return unknownFields.equals(other.unknownFields);
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSGID_FIELD_NUMBER;
            hash = (53 * hash) + getMsgId();
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MsgOuterClass.Msg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.Msg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.Msg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.Msg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.Msg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.Msg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.Msg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgOuterClass.Msg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgOuterClass.Msg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MsgOuterClass.Msg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgOuterClass.Msg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgOuterClass.Msg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MsgOuterClass.Msg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Msg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Msg)
                MsgOuterClass.MsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_Msg_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_Msg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MsgOuterClass.Msg.class, MsgOuterClass.Msg.Builder.class);
            }

            // Construct using MsgOuterClass.Msg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                msgId_ = 0;

                if (dataBuilder_ == null) {
                    data_ = null;
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_Msg_descriptor;
            }

            @Override
            public MsgOuterClass.Msg getDefaultInstanceForType() {
                return MsgOuterClass.Msg.getDefaultInstance();
            }

            @Override
            public MsgOuterClass.Msg build() {
                MsgOuterClass.Msg result = buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public MsgOuterClass.Msg buildPartial() {
                MsgOuterClass.Msg result = new MsgOuterClass.Msg(this);
                result.msgId_ = msgId_;
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                } else {
                    result.data_ = dataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MsgOuterClass.Msg) {
                    return mergeFrom((MsgOuterClass.Msg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MsgOuterClass.Msg other) {
                if (other == MsgOuterClass.Msg.getDefaultInstance()) return this;
                if (other.getMsgId() != 0) {
                    setMsgId(other.getMsgId());
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MsgOuterClass.Msg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MsgOuterClass.Msg) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int msgId_;

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public int getMsgId() {
                return msgId_;
            }

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public Builder setMsgId(int value) {

                msgId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public Builder clearMsgId() {

                msgId_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.Any data_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public boolean hasData() {
                return dataBuilder_ != null || data_ != null;
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                } else {
                    dataBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public Builder setData(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (data_ != null) {
                        data_ =
                                com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
                    } else {
                        data_ = value;
                    }
                    onChanged();
                } else {
                    dataBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = null;
                    onChanged();
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {

                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <code>.google.protobuf.Any Data = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Msg)
        }

        // @@protoc_insertion_point(class_scope:Msg)
        private static final MsgOuterClass.Msg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MsgOuterClass.Msg();
        }

        public static MsgOuterClass.Msg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Msg>
                PARSER = new com.google.protobuf.AbstractParser<Msg>() {
            @Override
            public Msg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Msg(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Msg> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Msg> getParserForType() {
            return PARSER;
        }

        @Override
        public MsgOuterClass.Msg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface EnterRoomUserToOtherOrBuilder extends
            // @@protoc_insertion_point(interface_extends:EnterRoomUserToOther)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 MsgId = 1;</code>
         */
        int getMsgId();

        /**
         * <code>int32 UserId = 2;</code>
         */
        int getUserId();

        /**
         * <code>string Name = 3;</code>
         */
        String getName();

        /**
         * <code>string Name = 3;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>int32 UserLevel = 4;</code>
         */
        int getUserLevel();

        /**
         * <code>int32 UserIdentity = 5;</code>
         */
        int getUserIdentity();

        /**
         * <code>int64 VisitorNum = 6;</code>
         */
        long getVisitorNum();
    }

    /**
     * <pre>
     * MsgId:4 ��һ���û����뷿���֪ͨ������������
     * </pre>
     * <p>
     * Protobuf type {@code EnterRoomUserToOther}
     */
    public static final class EnterRoomUserToOther extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:EnterRoomUserToOther)
            EnterRoomUserToOtherOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use EnterRoomUserToOther.newBuilder() to construct.
        private EnterRoomUserToOther(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private EnterRoomUserToOther() {
            name_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new EnterRoomUserToOther();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private EnterRoomUserToOther(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            msgId_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            userId_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 32: {

                            userLevel_ = input.readInt32();
                            break;
                        }
                        case 40: {

                            userIdentity_ = input.readInt32();
                            break;
                        }
                        case 48: {

                            visitorNum_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MsgOuterClass.internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MsgOuterClass.internal_static_Mua_ProtoMsg_EnterRoomUserToOther_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MsgOuterClass.EnterRoomUserToOther.class, MsgOuterClass.EnterRoomUserToOther.Builder.class);
        }

        public static final int MSGID_FIELD_NUMBER = 1;
        private int msgId_;

        /**
         * <code>int32 MsgId = 1;</code>
         */
        public int getMsgId() {
            return msgId_;
        }

        public static final int USERID_FIELD_NUMBER = 2;
        private int userId_;

        /**
         * <code>int32 UserId = 2;</code>
         */
        public int getUserId() {
            return userId_;
        }

        public static final int NAME_FIELD_NUMBER = 3;
        private volatile Object name_;

        /**
         * <code>string Name = 3;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string Name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int USERLEVEL_FIELD_NUMBER = 4;
        private int userLevel_;

        /**
         * <code>int32 UserLevel = 4;</code>
         */
        public int getUserLevel() {
            return userLevel_;
        }

        public static final int USERIDENTITY_FIELD_NUMBER = 5;
        private int userIdentity_;

        /**
         * <code>int32 UserIdentity = 5;</code>
         */
        public int getUserIdentity() {
            return userIdentity_;
        }

        public static final int VISITORNUM_FIELD_NUMBER = 6;
        private long visitorNum_;

        /**
         * <code>int64 VisitorNum = 6;</code>
         */
        public long getVisitorNum() {
            return visitorNum_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (msgId_ != 0) {
                output.writeInt32(1, msgId_);
            }
            if (userId_ != 0) {
                output.writeInt32(2, userId_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
            }
            if (userLevel_ != 0) {
                output.writeInt32(4, userLevel_);
            }
            if (userIdentity_ != 0) {
                output.writeInt32(5, userIdentity_);
            }
            if (visitorNum_ != 0L) {
                output.writeInt64(6, visitorNum_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (msgId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, msgId_);
            }
            if (userId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, userId_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
            }
            if (userLevel_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, userLevel_);
            }
            if (userIdentity_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, userIdentity_);
            }
            if (visitorNum_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(6, visitorNum_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MsgOuterClass.EnterRoomUserToOther)) {
                return super.equals(obj);
            }
            MsgOuterClass.EnterRoomUserToOther other = (MsgOuterClass.EnterRoomUserToOther) obj;

            if (getMsgId()
                    != other.getMsgId()) return false;
            if (getUserId()
                    != other.getUserId()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (getUserLevel()
                    != other.getUserLevel()) return false;
            if (getUserIdentity()
                    != other.getUserIdentity()) return false;
            if (getVisitorNum()
                    != other.getVisitorNum()) return false;
            return unknownFields.equals(other.unknownFields);
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSGID_FIELD_NUMBER;
            hash = (53 * hash) + getMsgId();
            hash = (37 * hash) + USERID_FIELD_NUMBER;
            hash = (53 * hash) + getUserId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + USERLEVEL_FIELD_NUMBER;
            hash = (53 * hash) + getUserLevel();
            hash = (37 * hash) + USERIDENTITY_FIELD_NUMBER;
            hash = (53 * hash) + getUserIdentity();
            hash = (37 * hash) + VISITORNUM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getVisitorNum());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MsgOuterClass.EnterRoomUserToOther parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MsgOuterClass.EnterRoomUserToOther prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * MsgId:4 ��һ���û����뷿���֪ͨ������������
         * </pre>
         * <p>
         * Protobuf type {@code EnterRoomUserToOther}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:EnterRoomUserToOther)
                MsgOuterClass.EnterRoomUserToOtherOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_EnterRoomUserToOther_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MsgOuterClass.EnterRoomUserToOther.class, MsgOuterClass.EnterRoomUserToOther.Builder.class);
            }

            // Construct using MsgOuterClass.EnterRoomUserToOther.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                msgId_ = 0;

                userId_ = 0;

                name_ = "";

                userLevel_ = 0;

                userIdentity_ = 0;

                visitorNum_ = 0L;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MsgOuterClass.internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor;
            }

            @Override
            public MsgOuterClass.EnterRoomUserToOther getDefaultInstanceForType() {
                return MsgOuterClass.EnterRoomUserToOther.getDefaultInstance();
            }

            @Override
            public MsgOuterClass.EnterRoomUserToOther build() {
                MsgOuterClass.EnterRoomUserToOther result = buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public MsgOuterClass.EnterRoomUserToOther buildPartial() {
                MsgOuterClass.EnterRoomUserToOther result = new MsgOuterClass.EnterRoomUserToOther(this);
                result.msgId_ = msgId_;
                result.userId_ = userId_;
                result.name_ = name_;
                result.userLevel_ = userLevel_;
                result.userIdentity_ = userIdentity_;
                result.visitorNum_ = visitorNum_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MsgOuterClass.EnterRoomUserToOther) {
                    return mergeFrom((MsgOuterClass.EnterRoomUserToOther) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MsgOuterClass.EnterRoomUserToOther other) {
                if (other == MsgOuterClass.EnterRoomUserToOther.getDefaultInstance())
                    return this;
                if (other.getMsgId() != 0) {
                    setMsgId(other.getMsgId());
                }
                if (other.getUserId() != 0) {
                    setUserId(other.getUserId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getUserLevel() != 0) {
                    setUserLevel(other.getUserLevel());
                }
                if (other.getUserIdentity() != 0) {
                    setUserIdentity(other.getUserIdentity());
                }
                if (other.getVisitorNum() != 0L) {
                    setVisitorNum(other.getVisitorNum());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MsgOuterClass.EnterRoomUserToOther parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MsgOuterClass.EnterRoomUserToOther) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int msgId_;

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public int getMsgId() {
                return msgId_;
            }

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public Builder setMsgId(int value) {

                msgId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 MsgId = 1;</code>
             */
            public Builder clearMsgId() {

                msgId_ = 0;
                onChanged();
                return this;
            }

            private int userId_;

            /**
             * <code>int32 UserId = 2;</code>
             */
            public int getUserId() {
                return userId_;
            }

            /**
             * <code>int32 UserId = 2;</code>
             */
            public Builder setUserId(int value) {

                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 UserId = 2;</code>
             */
            public Builder clearUserId() {

                userId_ = 0;
                onChanged();
                return this;
            }

            private Object name_ = "";

            /**
             * <code>string Name = 3;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string Name = 3;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string Name = 3;</code>
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 3;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 3;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                AbstractMessageLite.checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int userLevel_;

            /**
             * <code>int32 UserLevel = 4;</code>
             */
            public int getUserLevel() {
                return userLevel_;
            }

            /**
             * <code>int32 UserLevel = 4;</code>
             */
            public Builder setUserLevel(int value) {

                userLevel_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 UserLevel = 4;</code>
             */
            public Builder clearUserLevel() {

                userLevel_ = 0;
                onChanged();
                return this;
            }

            private int userIdentity_;

            /**
             * <code>int32 UserIdentity = 5;</code>
             */
            public int getUserIdentity() {
                return userIdentity_;
            }

            /**
             * <code>int32 UserIdentity = 5;</code>
             */
            public Builder setUserIdentity(int value) {

                userIdentity_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 UserIdentity = 5;</code>
             */
            public Builder clearUserIdentity() {

                userIdentity_ = 0;
                onChanged();
                return this;
            }

            private long visitorNum_;

            /**
             * <code>int64 VisitorNum = 6;</code>
             */
            public long getVisitorNum() {
                return visitorNum_;
            }

            /**
             * <code>int64 VisitorNum = 6;</code>
             */
            public Builder setVisitorNum(long value) {

                visitorNum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 VisitorNum = 6;</code>
             */
            public Builder clearVisitorNum() {

                visitorNum_ = 0L;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:EnterRoomUserToOther)
        }

        // @@protoc_insertion_point(class_scope:EnterRoomUserToOther)
        private static final MsgOuterClass.EnterRoomUserToOther DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MsgOuterClass.EnterRoomUserToOther();
        }

        public static MsgOuterClass.EnterRoomUserToOther getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<EnterRoomUserToOther>
                PARSER = new com.google.protobuf.AbstractParser<EnterRoomUserToOther>() {
            @Override
            public EnterRoomUserToOther parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new EnterRoomUserToOther(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<EnterRoomUserToOther> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<EnterRoomUserToOther> getParserForType() {
            return PARSER;
        }

        @Override
        public MsgOuterClass.EnterRoomUserToOther getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Mua_ProtoMsg_Msg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Mua_ProtoMsg_Msg_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Mua_ProtoMsg_EnterRoomUserToOther_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\tMsg.proto\022\014Mua.ProtoMsg\032\tany.proto\"8\n\003" +
                        "Msg\022\r\n\005MsgId\030\001 \001(\005\022\"\n\004Data\030\002 \001(\0132\024.googl" +
                        "e.protobuf.Any\"\200\001\n\024EnterRoomUserToOther\022" +
                        "\r\n\005MsgId\030\001 \001(\005\022\016\n\006UserId\030\002 \001(\005\022\014\n\004Name\030\003" +
                        " \001(\t\022\021\n\tUserLevel\030\004 \001(\005\022\024\n\014UserIdentity\030" +
                        "\005 \001(\005\022\022\n\nVisitorNum\030\006 \001(\003b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        });
        internal_static_Mua_ProtoMsg_Msg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Mua_ProtoMsg_Msg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Mua_ProtoMsg_Msg_descriptor,
                new String[]{"MsgId", "Data",});
        internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Mua_ProtoMsg_EnterRoomUserToOther_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Mua_ProtoMsg_EnterRoomUserToOther_descriptor,
                new String[]{"MsgId", "UserId", "Name", "UserLevel", "UserIdentity", "VisitorNum",});
        com.google.protobuf.AnyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
